//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba_salud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_invoices
    {
        public long id { get; set; }
        public long product_id { get; set; }
        public long invoice_id { get; set; }
        public int cant_prods { get; set; }
        public decimal sub_total { get; set; }
    
        public virtual invoice invoice { get; set; }
        public virtual product product { get; set; }
    }
}
